name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f17969f1937cfcf903b183ab7317394c2b9e8ee38f5784390ddccf3199dbf63"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
