name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd3429e6f8f8890eec811e9231c14eb829f0e05b1b0b3e136ac238ca013b190c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
