name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "054d1b740707fe2e1699350be335e65c32012ca7d5723cc90bd133f6fa854245"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
