name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4687bf951a93270d06e90146284e202b883f6caea3e4da778aded9c330890b11"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
