name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "870affd100e464b6501bd5686b9d9eb401d479f1f6d11c8b47fd0f748bbd690b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
