name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ef634125b8c1089010bd1365f78900776315feeb67954cb3c32436764f93ad7"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
