name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f852e6993351ef86aece199c871c579e8018cd170b5724bf5e8a5552ca163ea5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
