name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa772d1f6fb9147c797fa7b97d65980968c3905d6d223cff248d5fefd01ad73c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
