name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1bbc6ce42c7c75c510b7f52b00f3ed9e6c55ea06876d558af072b2b8ceba956"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
