name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c23c4cd6f30acf924c527e8be39286433985044fae8cf30309b26c1c73e12afa"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
