name = "Sweaty-Pack"
author = "Arte"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90a4db7343d461ddede1d93f8bbd1b826e6f92d9865ef7e5839f5d292542ac25"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
