name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18-1.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3618/332/InventoryProfilesNext-fabric-1.18-1.2.4.jar"
hash-format = "murmur2"
hash = "3026812331"

[update]
[update.curseforge]
file-id = 3618332
project-id = 495267
