name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.2.405.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/214/RoughlyEnoughItems-7.2.405.jar"
hash-format = "murmur2"
hash = "2295567821"

[update]
[update.curseforge]
file-id = 3625214
project-id = 310111
